version: '3.8'

networks: 
    postgres-compose-network:
      driver: bridge

volumes:
    postgres_vol:     
     
services:
  kube-news:
    image: eduardodamasio/kube-news:v1
    restart: always
    ports:
      - 8080:8080
    environment:
      DB_DATABASE: postgres
      DB_USERNAME: root 
      DB_PASSWORD: Postgres2022!
      DB_HOST: postgres
      
    depends_on:
      - postgres
    networks:
      - postgres-compose-network
    
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 80:80
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@email.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      
           
    depends_on:
      - postgres
    networks:
      - postgres-compose-network
    
  postgres:
    image: postgres:15.1
    restart: always
    ports:
      - 5432:5432 
    networks:
      - postgres-compose-network  
    volumes:
      - postgres_vol:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: Postgres2022!
      POSTGRES_USER: root